##################################################
#         Rackspace API configuration            #
##################################################

api:
    user: username
    api_key: api_key
    identity_url: https://identity.api.rackspacecloud.com/v2.0
    datacenter: IAD
    debug: True

##################################################
#        virtual machine configuraiton           #
##################################################

vm_build_data:
    config:
        image: vm-image
        flavor: 2
        base_name: benchmark-                        # will create benchmark-0, benchmark-1, etc
    how_many: 0
    source_dir: ~/trial-by-combat                    # this will be copied over to the nodes
    master_ip: master-ip-address                     # needed to open doorways in firewalls

##################################################
#            database configuration              #
##################################################

database_build_data:
    - flavor: "1"
      size: 1
      name: mysql_benchmark_db
      type: 1
      database_name: benchmark
      user: benchmark
      password: guest
      interface_id: MySQL
      auxilary_interface_data:                       # used to generate the interface yaml automatically
          port: 3306
          debug_queries: False
          debug_responses: False
